#!/usr/bin/env python3
"""wt.py - task workspaces: one folder per task, holding a git worktree of each repository it touches.

    <root>/<task>/<repo>/     a worktree of <repo>'s main checkout, on the task's branch

    wt.py init [--root PATH]                    show or set the root (user scope, asked once)
    wt.py repo add NAME PATH [--copy F]... [--setup CMD]
    wt.py repo list | repo remove NAME          the repositories tasks can use, by name
    wt.py new TASK REPO... [--branch B] [--base REF] [--no-fetch] [--note TEXT]
    wt.py add TASK REPO... [--no-fetch]         bring another repository into a task
    wt.py status [TASK...] [--fetch] [--json]   every task (or the named ones), and worktrees outside the root
    wt.py sync TASK [--rebase] [--no-fetch]     bring each repository up to date with its base
    wt.py run TASK -- CMD...                    run a command in each repository of a task
    wt.py remove TASK [--force]                 remove a task's worktrees and folder
    wt.py prune [--yes] [--no-fetch]            remove tasks whose every branch is already in its base

Nothing that holds work is lost. `remove` refuses a repository with uncommitted changes or commits no
remote has; --force saves the uncommitted changes as a patch under <root>/.removed/ first, and a branch
with unpushed commits is always kept. Only worktrees under the root are ever removed.

The root and the repository names live in ~/.config/adk/worktrees.json ($XDG_CONFIG_HOME respected;
ADK_WORKTREES_CONFIG and ADK_WORKTREES_ROOT override). Standard library only.
"""

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import time

META = ".adk-task.json"
BEGIN = "<!-- adk-worktrees: generated by wt.py, refreshed on add; write your own notes outside this block -->"
END = "<!-- adk-worktrees:end -->"
FETCH_TIMEOUT = 120
ENV = dict(os.environ, GIT_TERMINAL_PROMPT="0")  # a fetch never waits on a credential prompt


class Fail(Exception):
    pass


# ---------------------------------------------------------------- git

def git(cwd, *args, check=True, timeout=None):
    r = subprocess.run(["git", "-C", cwd, *args], capture_output=True, text=True, env=ENV, timeout=timeout)
    if check and r.returncode:
        raise Fail(f"git {' '.join(args)} in {cwd}: {(r.stderr or r.stdout).strip()}")
    return r.stdout.strip() if check else r


def ok(cwd, *args):
    return git(cwd, *args, check=False).returncode == 0


def main_checkout(path):
    common = git(path, "rev-parse", "--path-format=absolute", "--git-common-dir")
    return os.path.dirname(common) if os.path.basename(common) == ".git" else common


def fetch(src):
    if "origin" not in git(src, "remote").split():
        return None
    try:
        r = git(src, "fetch", "--quiet", "--prune", "origin", check=False, timeout=FETCH_TIMEOUT)
    except subprocess.TimeoutExpired:
        return f"fetch timed out after {FETCH_TIMEOUT}s - using what is already fetched"
    return None if r.returncode == 0 else f"fetch failed ({r.stderr.strip()[:200]}) - using what is already fetched"


def default_base(src):
    r = git(src, "symbolic-ref", "-q", "--short", "refs/remotes/origin/HEAD", check=False)
    if r.returncode == 0 and r.stdout.strip():
        return r.stdout.strip()
    for ref in ("origin/main", "origin/master", "main", "master"):
        if ok(src, "rev-parse", "-q", "--verify", ref + "^{commit}"):
            return ref
    return git(src, "rev-parse", "--abbrev-ref", "HEAD")


def count(cwd, *args):
    r = git(cwd, *args, check=False)
    return int(r.stdout.strip()) if r.returncode == 0 and r.stdout.strip().isdigit() else None


# ---------------------------------------------------------------- config

def config_path():
    if os.environ.get("ADK_WORKTREES_CONFIG"):
        return os.environ["ADK_WORKTREES_CONFIG"]
    base = os.environ.get("XDG_CONFIG_HOME") or os.path.join(os.path.expanduser("~"), ".config")
    return os.path.join(base, "adk", "worktrees.json")


def load_config():
    try:
        with open(config_path()) as f:
            cfg = json.load(f)
    except FileNotFoundError:
        cfg = {}
    cfg.setdefault("repos", {})
    for name, entry in list(cfg["repos"].items()):
        cfg["repos"][name] = {"path": entry} if isinstance(entry, str) else entry
    return cfg


def save_config(cfg):
    path = config_path()
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        json.dump(cfg, f, indent=2)
        f.write("\n")


def root_of(cfg):
    root = os.environ.get("ADK_WORKTREES_ROOT") or cfg.get("root")
    if not root:
        raise Fail("No worktree root is set. Ask the user where task folders should live, then run:\n"
                   "  wt.py init --root <path>")
    return os.path.realpath(os.path.expanduser(root))


def resolve_repo(cfg, arg):
    """A registered name, or a path to a checkout (registered by its folder name on first use)."""
    if arg in cfg["repos"]:
        entry = cfg["repos"][arg]
        if not os.path.isdir(entry["path"]):
            raise Fail(f"{arg}: its main checkout {entry['path']} is gone - wt.py repo add {arg} <new path>")
        return arg, entry
    path = os.path.realpath(os.path.expanduser(arg))
    if not os.path.isdir(path) or not ok(path, "rev-parse", "--git-dir"):
        have = ", ".join(sorted(cfg["repos"])) or "none yet"
        raise Fail(f"{arg}: not a registered repository ({have}) nor a path to a git checkout")
    src = main_checkout(path)
    name = os.path.basename(src)
    known = cfg["repos"].get(name)
    if known and os.path.realpath(known["path"]) != src:
        raise Fail(f"{arg}: the name {name} is already {known['path']} - register this one under another "
                   f"name: wt.py repo add <name> {src}")
    if not known:
        cfg["repos"][name] = {"path": src}
        save_config(cfg)
        print(f"registered {name} -> {src}")
    return name, cfg["repos"][name]


# ---------------------------------------------------------------- tasks

def task_dir(root, task):
    return os.path.join(root, task)


def load_task(root, task):
    try:
        with open(os.path.join(task_dir(root, task), META)) as f:
            return json.load(f)
    except FileNotFoundError:
        raise Fail(f"no task {task} under {root}") from None


def save_task(root, meta):
    with open(os.path.join(task_dir(root, meta["task"]), META), "w") as f:
        json.dump(meta, f, indent=2)
        f.write("\n")
    write_claude_md(root, meta)


def all_tasks(root):
    if not os.path.isdir(root):
        return []
    return sorted(d for d in os.listdir(root) if os.path.isfile(os.path.join(root, d, META)))


def write_claude_md(root, meta):
    """The task folder's CLAUDE.md: what the task is and where each repository's own instructions are."""
    d = task_dir(root, meta["task"])
    lines = [BEGIN, f"# Task: {meta['task']}", ""]
    if meta.get("note"):
        lines += [meta["note"], ""]
    lines += [f"Each folder below is a git worktree on branch `{meta['branch']}`. This folder itself is not a "
              "repository: run git per repository (`git -C <folder> ...`), and commit, push and open a pull "
              "request in each one separately.", "",
              "| Folder | Base | Main checkout |", "|---|---|---|"]
    for name, r in meta["repos"].items():
        lines.append(f"| `{name}/` | `{r['base']}` | `{r['source']}` |")
    imports = [f"@{name}/CLAUDE.md" for name in meta["repos"] if os.path.isfile(os.path.join(d, name, "CLAUDE.md"))]
    if imports:
        lines += ["", "Each repository's own instructions:", *imports]
    block = "\n".join(lines + [END])
    path = os.path.join(d, "CLAUDE.md")
    try:
        with open(path) as f:
            text = f.read()
    except FileNotFoundError:
        text = ""
    if BEGIN in text and END in text:
        text = text[:text.index(BEGIN)] + block + text[text.index(END) + len(END):]
    else:
        text = block + "\n" + (("\n" + text) if text else "")
    with open(path, "w") as f:
        f.write(text)


def attach(name, entry, path, branch, base):
    """Create the worktree; returns whether the branch was created here (so a rollback deletes it)."""
    src = entry["path"]
    if ok(src, "show-ref", "--verify", "-q", f"refs/heads/{branch}"):
        git(src, "worktree", "add", path, branch)
        created = False
    elif ok(src, "show-ref", "--verify", "-q", f"refs/remotes/origin/{branch}"):
        git(src, "worktree", "add", "--track", "-b", branch, path, f"origin/{branch}")
        created = True
    else:
        if not ok(src, "rev-parse", "-q", "--verify", base + "^{commit}"):
            raise Fail(f"{name}: base {base} does not exist")
        git(src, "worktree", "add", "--no-track", "-b", branch, path, base)
        created = True
    for rel in entry.get("copy", []):
        s, d = os.path.join(src, rel), os.path.join(path, rel)
        if os.path.exists(s) and not os.path.exists(d):
            os.makedirs(os.path.dirname(d), exist_ok=True)
            (shutil.copytree if os.path.isdir(s) else shutil.copy2)(s, d)
            print(f"  {name}: copied {rel} from the main checkout")
    return created


def setup(name, entry, path):
    if entry.get("setup"):
        print(f"  {name}: {entry['setup']}")
        if subprocess.run(entry["setup"], shell=True, cwd=path).returncode:
            print(f"  {name}: setup failed - the worktree is there; run it again by hand")


def add_repos(cfg, root, meta, args, do_fetch):
    """Attach each repository to the task, all or none: a failure removes what this call created."""
    d = task_dir(root, meta["task"])
    resolved = [resolve_repo(cfg, a) for a in args]
    names = [n for n, _ in resolved]
    for n in names:
        if n in meta["repos"] or names.count(n) > 1:
            raise Fail(f"{n} is already in task {meta['task']}")
    made = []
    try:
        for name, entry in resolved:
            src = entry["path"]
            if do_fetch:
                warn = fetch(src)
                if warn:
                    print(f"  {name}: {warn}")
            base = meta.get("base") or default_base(src)
            path = os.path.join(d, name)
            made.append((name, src, path, attach(name, entry, path, meta["branch"], base)))
            meta["repos"][name] = {"source": src, "base": base}
            print(f"  {name}: {os.path.relpath(path, root)} on {meta['branch']} (base {base})")
    except Exception:
        for name, src, path, created in reversed(made):
            git(src, "worktree", "remove", "--force", path, check=False)
            if created:
                git(src, "branch", "-D", meta["branch"], check=False)
            meta["repos"].pop(name, None)
        raise
    for name, entry in resolved:
        setup(name, entry, os.path.join(d, name))


# ---------------------------------------------------------------- state

def repo_state(path, base):
    if not os.path.isdir(path):
        return {"state": "missing"}
    branch = git(path, "symbolic-ref", "-q", "--short", "HEAD", check=False).stdout.strip() or "(detached)"
    dirty = len(git(path, "status", "--porcelain", "--untracked-files=normal").splitlines())
    counts = git(path, "rev-list", "--left-right", "--count", f"{base}...HEAD", check=False)
    behind = ahead = None
    if counts.returncode == 0:
        behind, ahead = (int(x) for x in counts.stdout.split())
    if git(path, "remote").split():
        unpushed = count(path, "rev-list", "--count", "HEAD", "--not", "--remotes")
    else:
        unpushed = ahead
    track = git(path, "for-each-ref", "--format=%(upstream:short)|%(upstream:track)", f"refs/heads/{branch}",
                check=False).stdout.strip()
    upstream, _, t = track.partition("|")
    gone = "[gone]" in t
    if dirty:
        state = "uncommitted"
    elif unpushed and gone:
        state = "remote-gone"          # typical after a squash merge deleted the remote branch
    elif unpushed:
        state = "unpushed"
    elif ahead == 0:
        state = "in-base"              # everything on the branch is already in its base
    else:
        state = "pushed"
    return {"state": state, "branch": branch, "ahead": ahead, "behind": behind, "uncommitted": dirty,
            "unpushed": unpushed or 0, "upstream": upstream or None, "upstream_gone": gone}


def task_state(root, task, do_fetch=False):
    meta = load_task(root, task)
    out = {"task": task, "branch": meta["branch"], "note": meta.get("note"), "repos": {}}
    for name, r in meta["repos"].items():
        if do_fetch and os.path.isdir(r["source"]):
            fetch(r["source"])
        out["repos"][name] = repo_state(os.path.join(task_dir(root, task), name), r["base"])
        out["repos"][name]["base"] = r["base"]
    return out


def strays(cfg, root):
    """Worktrees of registered repositories that are outside the root (the kit's own unit worktrees aside)."""
    found = []
    for name, entry in sorted(cfg["repos"].items()):
        src = entry["path"]
        if not os.path.isdir(src):
            continue
        for line in git(src, "worktree", "list", "--porcelain", check=False).stdout.splitlines():
            if not line.startswith("worktree "):
                continue
            p = os.path.realpath(line[9:])
            if p == os.path.realpath(src) or p.startswith(root + os.sep) or "/.claude/worktrees/" in p:
                continue
            found.append((name, p))
    return found


def fmt(v):
    return "-" if v is None else str(v)


# ---------------------------------------------------------------- commands

def cmd_init(cfg, a):
    if a.root:
        root = os.path.realpath(os.path.expanduser(a.root))
        os.makedirs(root, exist_ok=True)
        cfg["root"] = root
        save_config(cfg)
    print(f"config: {config_path()}")
    print(f"root:   {cfg.get('root') or '(not set)'}")
    print(f"repos:  {', '.join(sorted(cfg['repos'])) or '(none)'}")


def cmd_repo(cfg, a):
    if a.repo_cmd == "add":
        path = os.path.realpath(os.path.expanduser(a.path))
        if not os.path.isdir(path) or not ok(path, "rev-parse", "--git-dir"):
            raise Fail(f"{a.path} is not a git checkout")
        entry = {"path": main_checkout(path)}
        if a.copy:
            entry["copy"] = a.copy
        if a.setup:
            entry["setup"] = a.setup
        cfg["repos"][a.name] = entry
        save_config(cfg)
        print(f"{a.name} -> {entry['path']}")
    elif a.repo_cmd == "remove":
        if cfg["repos"].pop(a.name, None) is None:
            raise Fail(f"no repository named {a.name}")
        save_config(cfg)
        print(f"forgot {a.name} (its checkout and worktrees are untouched)")
    else:
        for name, e in sorted(cfg["repos"].items()):
            extra = "".join([f"  copy {','.join(e['copy'])}" if e.get("copy") else "",
                             f"  setup `{e['setup']}`" if e.get("setup") else ""])
            print(f"{name}  {e['path']}{extra}")


def cmd_new(cfg, a):
    root = root_of(cfg)
    if not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9._-]*", a.task):
        raise Fail(f"task name {a.task!r}: letters, digits, '.', '_' and '-' only - it is a folder name")
    branch = a.branch or a.task
    if subprocess.run(["git", "check-ref-format", "--branch", branch], capture_output=True).returncode:
        raise Fail(f"{branch!r} is not a valid branch name")
    d = task_dir(root, a.task)
    if os.path.exists(d):
        raise Fail(f"{d} already exists - wt.py add {a.task} <repo> to bring in another repository")
    os.makedirs(d)
    meta = {"task": a.task, "branch": branch, "created": time.strftime("%Y-%m-%d"), "repos": {}}
    if a.base:
        meta["base"] = a.base
    if a.note:
        meta["note"] = a.note
    print(f"task {a.task} at {d}")
    try:
        add_repos(cfg, root, meta, a.repos, not a.no_fetch)
    except Exception:
        shutil.rmtree(d, ignore_errors=True)
        raise
    save_task(root, meta)
    print(f"open it: cd {d}")


def cmd_add(cfg, a):
    root = root_of(cfg)
    meta = load_task(root, a.task)
    add_repos(cfg, root, meta, a.repos, not a.no_fetch)
    save_task(root, meta)


def cmd_status(cfg, a):
    root = root_of(cfg)
    tasks = a.tasks or all_tasks(root)
    states = [task_state(root, t, a.fetch) for t in tasks]
    others = [] if a.tasks else strays(cfg, root)
    if a.json:
        print(json.dumps({"root": root, "tasks": states,
                          "outside_root": [{"repo": n, "path": p} for n, p in others]}, indent=2))
        return
    if not states:
        print(f"No tasks under {root}.")
    for s in states:
        print(f"{s['task']}  branch {s['branch']}" + (f"  - {s['note']}" if s.get("note") else ""))
        width = max(len(n) for n in s["repos"]) if s["repos"] else 0
        for name, r in s["repos"].items():
            if r["state"] == "missing":
                print(f"  {name:<{width}}  missing - the folder is gone")
                continue
            print(f"  {name:<{width}}  {r['state']:<11}  ahead {fmt(r['ahead'])}  behind {fmt(r['behind'])}"
                  f"  uncommitted {r['uncommitted']}  unpushed {r['unpushed']}  base {r['base']}"
                  + ("" if r["branch"] == s["branch"] else f"  (on {r['branch']}, not the task's branch)"))
    if others:
        print("\nWorktrees outside the root:")
        for name, p in others:
            print(f"  {name}  {p}")


def cmd_sync(cfg, a):
    root = root_of(cfg)
    meta = load_task(root, a.task)
    failed = False
    for name, r in meta["repos"].items():
        path = os.path.join(task_dir(root, a.task), name)
        if not a.no_fetch:
            warn = fetch(r["source"])
            if warn:
                print(f"  {name}: {warn}")
        s = repo_state(path, r["base"])
        skip = None
        if s["state"] == "missing":
            skip = "missing - the folder is gone"
        elif s["uncommitted"]:
            skip = f"skipped - {s['uncommitted']} uncommitted change(s); commit or stash first"
        elif a.rebase and s["upstream"] and count(path, "rev-list", "--count", f"{r['base']}..{s['upstream']}"):
            skip = "skipped - the branch is pushed; rebasing would need a force push. Sync without --rebase"
        if skip:
            print(f"  {name}: {skip}")
            failed = True
            continue
        if s["behind"] == 0:
            print(f"  {name}: up to date with {r['base']}")
            continue
        step = ["rebase", r["base"]] if a.rebase else ["merge", "--no-edit", r["base"]]
        if ok(path, *step):
            print(f"  {name}: {'rebased onto' if a.rebase else 'merged'} {r['base']} ({s['behind']} commit(s))")
            continue
        conflicts = git(path, "diff", "--name-only", "--diff-filter=U", check=False).stdout.split()
        git(path, step[0], "--abort", check=False)
        print(f"  {name}: conflicts with {r['base']} in {', '.join(conflicts) or 'the tree'} - left as it was; "
              f"run `git -C {name} {' '.join(step)}` and resolve them")
        failed = True
    return 1 if failed else 0


def cmd_run(cfg, a):
    root = root_of(cfg)
    meta = load_task(root, a.task)
    cmd = a.command[1:] if a.command and a.command[0] == "--" else a.command
    if not cmd:
        raise Fail("nothing to run: wt.py run TASK -- <command>")
    failed = []
    for name in meta["repos"]:
        print(f"== {name}", flush=True)
        shell = len(cmd) == 1
        rc = subprocess.run(cmd[0] if shell else cmd, shell=shell, cwd=os.path.join(task_dir(root, a.task), name)).returncode
        if rc:
            failed.append(f"{name} ({rc})")
    if failed:
        print(f"failed in: {', '.join(failed)}")
    return 1 if failed else 0


def remove_task(root, task, force):
    meta = load_task(root, task)
    d = task_dir(root, task)
    states = {n: repo_state(os.path.join(d, n), r["base"]) for n, r in meta["repos"].items()}
    holding = {n: s for n, s in states.items() if s["state"] in ("uncommitted", "unpushed", "remote-gone")}
    if holding and not force:
        lines = [f"  {n}: {s['uncommitted']} uncommitted, {s['unpushed']} unpushed commit(s)"
                 + (" - its remote branch is gone: if the pull request was merged (squash), --force is safe"
                    if s["upstream_gone"] else "") for n, s in holding.items()]
        raise Fail(f"{task} holds work that would be lost:\n" + "\n".join(lines) +
                   "\nPush or commit it, or pass --force: uncommitted changes are saved as a patch and "
                   "branches with unpushed commits are kept.")
    for name, r in meta["repos"].items():
        path, s = os.path.join(d, name), states[name]
        if s["state"] != "missing":
            if s["uncommitted"]:
                keep = os.path.join(root, ".removed", task)
                os.makedirs(keep, exist_ok=True)
                patch = os.path.join(keep, f"{name}.patch")
                git(path, "add", "-A", "-N", ".", check=False)
                with open(patch, "w") as f:
                    f.write(git(path, "diff", "--binary", "HEAD", check=False).stdout)
                print(f"  {name}: uncommitted changes saved to {patch}")
            git(r["source"], "worktree", "remove", "--force", path)
        git(r["source"], "worktree", "prune", check=False)
        if s.get("unpushed"):
            print(f"  {name}: removed; kept branch {meta['branch']} ({s['unpushed']} unpushed commit(s))")
        elif ok(r["source"], "branch", "-d", meta["branch"]):
            print(f"  {name}: removed, with its branch")
        else:
            print(f"  {name}: removed; kept branch {meta['branch']} (not merged locally)")
    for f in (META, "CLAUDE.md"):
        try:
            os.remove(os.path.join(d, f))
        except FileNotFoundError:
            pass
    left = os.listdir(d) if os.path.isdir(d) else []
    if left:
        print(f"  kept {d}: it still holds {', '.join(sorted(left))}")
    else:
        os.rmdir(d)
        print(f"removed {task}")


def cmd_remove(cfg, a):
    remove_task(root_of(cfg), a.task, a.force)


def cmd_prune(cfg, a):
    root = root_of(cfg)
    done, check = [], []
    for t in all_tasks(root):
        s = task_state(root, t, not a.no_fetch)
        states = {r["state"] for r in s["repos"].values()}
        if s["repos"] and states <= {"in-base", "missing"}:
            done.append(t)
        elif "remote-gone" in states:
            check.append(t)
    for t in done:
        if a.yes:
            remove_task(root, t, False)
        else:
            print(f"would remove {t}: every branch is already in its base")
    for t in check:
        print(f"check {t}: a remote branch is gone but its commits are not in the base - "
              "if its pull requests were squash-merged, wt.py remove --force")
    if not done and not check:
        print("Nothing to prune.")
    elif done and not a.yes:
        print("Run again with --yes to remove them.")


def parser():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = p.add_subparsers(dest="cmd", required=True)
    sub.add_parser("init").add_argument("--root")

    repo = sub.add_parser("repo").add_subparsers(dest="repo_cmd", required=True)
    r = repo.add_parser("add")
    r.add_argument("name")
    r.add_argument("path")
    r.add_argument("--copy", action="append", help="an untracked file to copy into each new worktree, e.g. .env")
    r.add_argument("--setup", help="a command to run in each new worktree, e.g. 'npm ci'")
    repo.add_parser("list")
    repo.add_parser("remove").add_argument("name")

    s = sub.add_parser("new")
    s.add_argument("task")
    s.add_argument("repos", nargs="+")
    s.add_argument("--branch", help="default: the task name")
    s.add_argument("--base", help="default: each repository's origin/HEAD")
    s.add_argument("--note", help="one line on what the task is, for its CLAUDE.md")
    s.add_argument("--no-fetch", action="store_true")

    s = sub.add_parser("add")
    s.add_argument("task")
    s.add_argument("repos", nargs="+")
    s.add_argument("--no-fetch", action="store_true")

    s = sub.add_parser("status")
    s.add_argument("tasks", nargs="*")
    s.add_argument("--fetch", action="store_true")
    s.add_argument("--json", action="store_true")

    s = sub.add_parser("sync")
    s.add_argument("task")
    s.add_argument("--rebase", action="store_true")
    s.add_argument("--no-fetch", action="store_true")

    s = sub.add_parser("run")
    s.add_argument("task")
    s.add_argument("command", nargs=argparse.REMAINDER)

    s = sub.add_parser("remove")
    s.add_argument("task")
    s.add_argument("--force", action="store_true")

    s = sub.add_parser("prune")
    s.add_argument("--yes", action="store_true")
    s.add_argument("--no-fetch", action="store_true")
    return p


def main(argv=None):
    p = parser()
    a = p.parse_args(argv)
    try:
        return globals()["cmd_" + a.cmd](load_config(), a) or 0
    except Fail as e:
        print(f"wt.py: {e}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
