#!/usr/bin/env python3
"""wt.py - task workspaces: one folder per task, holding a checkout of every repository the task needs.

    <root>/<task>/task.json      the manifest: each repository's role and version, the task's build and test
    <root>/<task>/<repo>/        a git worktree of <repo>'s main checkout
    <root>/<task>/checks.jsonl   every check: what ran, the result, and the commit of each repository it ran on

A repository has a role in a task:
    edit         a worktree on the task's branch, from the repository's base (REPO@BASE to pick one)
    dependency   a worktree detached at a pinned ref (REPO@REF: a tag, a branch, a commit), to build against

    wt.py init [--root PATH] [--sources PATH]          show or set the root, and where restore clones to
    wt.py repo add NAME PATH [--copy F]... [--setup CMD]
    wt.py repo list | repo remove NAME                 the repositories tasks can use, by name
    wt.py new TASK [REPO[@BASE]...] [--dep REPO[@REF]]... [--branch B] [--base REF] [--note TEXT]
              [--extra SRC[:DEST]]... [--build CMD]... [--test CMD]... [--no-fetch]
    wt.py restore MANIFEST [--as TASK] [--no-fetch]    rebuild a task from a task.json, on this machine or another
    wt.py add TASK [REPO[@BASE]...] [--dep REPO[@REF]]... [--no-fetch]
    wt.py pin TASK REPO REF [--no-fetch]               move a dependency to another ref
    wt.py refresh TASK                                 regenerate CLAUDE.md and task.env after editing task.json
    wt.py status [TASK...] [--fetch] [--json]          every task (or the named ones), and worktrees outside the root
    wt.py sync TASK [--rebase] [--no-fetch]            bring each edit repository up to date with its base
    wt.py run TASK [--all] -- CMD...                   a command in each edit repository (--all: dependencies too)
    wt.py check TASK [-- CMD...]                       the task's build and test, run together, and recorded
    wt.py remove TASK [--force]                        remove a task's worktrees and folder
    wt.py prune [--yes] [--no-fetch]                   remove tasks whose every branch is already in its base

Nothing that holds work is lost. `remove` refuses a repository with uncommitted changes or commits no
remote has; --force saves the uncommitted changes as a patch under <root>/.removed/<task>/ first, keeps a
branch with unpushed commits, and keeps the manifest there too, so `restore` can bring the task back.
Only worktrees under the root are ever removed.

Each task gets its own environment (task.env, and every command run/check/--setup starts): ADK_TASK,
ADK_TASK_DIR, ADK_TASK_CACHE (a cache folder of its own), ADK_PORT_OFFSET (unique among the root's
tasks), COMPOSE_PROJECT_NAME, and the manifest's own "env", which may use ${ADK_...}.

The root and the repository names live in ~/.config/adk/worktrees.json ($XDG_CONFIG_HOME respected;
ADK_WORKTREES_CONFIG and ADK_WORKTREES_ROOT override). Standard library only.
"""

import argparse
import json
import os
import re
import shlex
import shutil
import subprocess
import sys
import time

try:
    import fcntl
except ImportError:  # not on Windows: config writes are then unlocked
    fcntl = None

MANIFEST = "task.json"
LEGACY = ".adk-task.json"  # the manifest's name before 0.22
CHECKS = "checks.jsonl"
ENVFILE = "task.env"
CACHE = ".cache"
GENERATED = (MANIFEST, LEGACY, "CLAUDE.md", ENVFILE)
BEGIN = "<!-- adk-worktrees: generated by wt.py, refreshed on add and refresh; write your own notes outside this block -->"
END = "<!-- adk-worktrees:end -->"
FETCH_TIMEOUT = 120
ENV = dict(os.environ, GIT_TERMINAL_PROMPT="0")  # a fetch never waits on a credential prompt
SCRIPT = os.path.abspath(__file__)


class Fail(Exception):
    pass


# ---------------------------------------------------------------- git

def git(cwd, *args, check=True, timeout=None):
    r = subprocess.run(["git", "-C", cwd, *args], capture_output=True, text=True, env=ENV, timeout=timeout)
    if check and r.returncode:
        raise Fail(f"git {' '.join(args)} in {cwd}: {(r.stderr or r.stdout).strip()}")
    return r.stdout.strip() if check else r


def ok(cwd, *args):
    return git(cwd, *args, check=False).returncode == 0


def main_checkout(path):
    common = git(path, "rev-parse", "--path-format=absolute", "--git-common-dir")
    return os.path.dirname(common) if os.path.basename(common) == ".git" else common


def fetch(src):
    if "origin" not in git(src, "remote").split():
        return None
    try:
        r = git(src, "fetch", "--quiet", "--prune", "--tags", "origin", check=False, timeout=FETCH_TIMEOUT)
    except subprocess.TimeoutExpired:
        return f"fetch timed out after {FETCH_TIMEOUT}s - using what is already fetched"
    return None if r.returncode == 0 else f"fetch failed ({r.stderr.strip()[:200]}) - using what is already fetched"


def default_base(src):
    r = git(src, "symbolic-ref", "-q", "--short", "refs/remotes/origin/HEAD", check=False)
    if r.returncode == 0 and r.stdout.strip():
        return r.stdout.strip()
    for ref in ("origin/main", "origin/master", "main", "master"):
        if ok(src, "rev-parse", "-q", "--verify", ref + "^{commit}"):
            return ref
    return git(src, "rev-parse", "--abbrev-ref", "HEAD")


def resolve_ref(src, ref):
    """A ref as the team has it now: a branch name means origin's copy when there is one. -> (name, sha)."""
    name = f"origin/{ref}" if ok(src, "show-ref", "--verify", "-q", f"refs/remotes/origin/{ref}") else ref
    r = git(src, "rev-parse", "-q", "--verify", name + "^{commit}", check=False)
    return (name, r.stdout.strip()) if r.returncode == 0 else (None, None)


def origin_url(src):
    r = git(src, "remote", "get-url", "origin", check=False)
    return r.stdout.strip() if r.returncode == 0 else None


def same_url(a, b):
    norm = lambda u: re.sub(r"(\.git)?/*$", "", u.strip())
    return norm(a) == norm(b)


def count(cwd, *args):
    r = git(cwd, *args, check=False)
    return int(r.stdout.strip()) if r.returncode == 0 and r.stdout.strip().isdigit() else None


# ---------------------------------------------------------------- config

def config_path():
    if os.environ.get("ADK_WORKTREES_CONFIG"):
        return os.environ["ADK_WORKTREES_CONFIG"]
    base = os.environ.get("XDG_CONFIG_HOME") or os.path.join(os.path.expanduser("~"), ".config")
    return os.path.join(base, "adk", "worktrees.json")


def load_config():
    try:
        with open(config_path()) as f:
            cfg = json.load(f)
    except FileNotFoundError:
        cfg = {}
    cfg.setdefault("repos", {})
    for name, entry in list(cfg["repos"].items()):
        cfg["repos"][name] = {"path": entry} if isinstance(entry, str) else entry
    return cfg


def update_config(cfg, change):
    """Apply change() to the config as it is on disk now, under a lock: two sessions registering at once both land."""
    path = config_path()
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path + ".lock", "a") as lock:
        if fcntl:
            fcntl.flock(lock, fcntl.LOCK_EX)
        fresh = load_config()
        result = change(fresh)
        tmp = path + ".tmp"
        with open(tmp, "w") as f:
            json.dump(fresh, f, indent=2)
            f.write("\n")
        os.replace(tmp, path)
    cfg.clear()
    cfg.update(fresh)
    return result


def root_of(cfg):
    root = os.environ.get("ADK_WORKTREES_ROOT") or cfg.get("root")
    if not root:
        raise Fail("No worktree root is set. Ask the user where task folders should live, then run:\n"
                   "  wt.py init --root <path>")
    return os.path.realpath(os.path.expanduser(root))


def register(cfg, name, src):
    def change(c):
        known = c["repos"].get(name)
        if known and os.path.realpath(known["path"]) != src:
            raise Fail(f"the name {name} is already {known['path']} - register this one under another "
                       f"name: wt.py repo add <name> {src}")
        if not known:
            c["repos"][name] = {"path": src}
            return True
        return False
    if update_config(cfg, change):
        print(f"registered {name} -> {src}")
    return cfg["repos"][name]


def split_spec(arg):
    """REPO@REF -> (REPO, REF). A path that exists and holds an @ is a path."""
    if "@" in arg and not os.path.exists(os.path.expanduser(arg)):
        left, _, right = arg.rpartition("@")
        if left and right:
            return left, right
    return arg, None


def resolve_repo(cfg, arg):
    """A registered name, or a path to a checkout (registered by its folder name on first use)."""
    if arg in cfg["repos"]:
        entry = cfg["repos"][arg]
        if not os.path.isdir(entry["path"]):
            raise Fail(f"{arg}: its main checkout {entry['path']} is gone - wt.py repo add {arg} <new path>")
        return arg, entry
    path = os.path.realpath(os.path.expanduser(arg))
    if not os.path.isdir(path) or not ok(path, "rev-parse", "--git-dir"):
        have = ", ".join(sorted(cfg["repos"])) or "none yet"
        raise Fail(f"{arg}: not a registered repository ({have}) nor a path to a git checkout")
    src = main_checkout(path)
    name = os.path.basename(src)
    try:
        return name, register(cfg, name, src)
    except Fail as e:
        raise Fail(f"{arg}: {e}") from None


def locate(cfg, name, r):
    """Where a manifest's repository is on this machine: registered, at its recorded path, or cloned from its url."""
    url = r.get("url")
    if name in cfg["repos"]:
        entry = cfg["repos"][name]
        if not os.path.isdir(entry["path"]):
            raise Fail(f"{name}: its main checkout {entry['path']} is gone - wt.py repo add {name} <new path>")
        have = origin_url(entry["path"])
        if url and have and not same_url(have, url):
            raise Fail(f"{name}: registered here as {entry['path']}, whose origin is {have}, not {url} - "
                       f"register the right checkout: wt.py repo add {name} <path>")
        return entry
    src = r.get("source")
    if src and os.path.isdir(src) and ok(src, "rev-parse", "--git-dir"):
        src = main_checkout(src)
        have = origin_url(src)
        if not url or not have or same_url(have, url):
            return register(cfg, name, src)
    sources = cfg.get("sources")
    if url and sources:
        sources = os.path.realpath(os.path.expanduser(sources))
        dest = os.path.join(sources, name)
        if not os.path.exists(dest):
            os.makedirs(sources, exist_ok=True)
            print(f"  {name}: cloning {url} into {dest}")
            git(sources, "clone", "--quiet", url, dest)
        elif not ok(dest, "rev-parse", "--git-dir") or not same_url(origin_url(dest) or "", url):
            raise Fail(f"{name}: {dest} exists and is not a clone of {url}")
        return register(cfg, name, dest)
    if not url:
        raise Fail(f"{name}: not on this machine, and the manifest has no url for it - register its checkout: "
                   f"wt.py repo add {name} <path>")
    raise Fail(f"{name}: not on this machine - register its checkout (wt.py repo add {name} <path>), or set a "
               f"folder to clone {url} into (wt.py init --sources <path>)")


# ---------------------------------------------------------------- tasks

def task_dir(root, task):
    return os.path.join(root, task)


def is_task(path):
    return os.path.isfile(os.path.join(path, MANIFEST)) or os.path.isfile(os.path.join(path, LEGACY))


def normalize(meta):
    if "repositories" not in meta:          # 0.21: every repository on the task's branch
        meta["repositories"] = {n: dict(r, role="edit") for n, r in meta.pop("repos", {}).items()}
    for key, empty in (("external_paths", list), ("build", list), ("test", list), ("env", dict), ("runtime", dict)):
        meta.setdefault(key, empty())
    return meta


def load_task(root, task):
    d = task_dir(root, task)
    for name in (MANIFEST, LEGACY):
        try:
            with open(os.path.join(d, name)) as f:
                return normalize(json.load(f))
        except FileNotFoundError:
            continue
    raise Fail(f"no task {task} under {root}")


def all_tasks(root):
    if not os.path.isdir(root):
        return []
    return sorted(d for d in os.listdir(root) if not d.startswith(".") and is_task(os.path.join(root, d)))


def free_port_offset(root, task):
    used = set()
    for t in all_tasks(root):
        if t != task:
            used.add(load_task(root, t)["runtime"].get("port_offset"))
    n = 100
    while n in used:
        n += 100
    return n


def save_task(root, meta):
    d = task_dir(root, meta["task"])
    meta["runtime"].setdefault("port_offset", free_port_offset(root, meta["task"]))
    keys = ("task", "branch", "base", "note", "created", "repositories", "external_paths", "build", "test",
            "env", "runtime")
    ordered = {k: meta[k] for k in keys if k in meta}
    ordered.update({k: v for k, v in meta.items() if k not in ordered})
    with open(os.path.join(d, MANIFEST), "w") as f:
        json.dump(ordered, f, indent=2)
        f.write("\n")
    if os.path.exists(os.path.join(d, LEGACY)):
        os.remove(os.path.join(d, LEGACY))
    write_claude_md(root, meta)
    write_env(root, meta)


def task_env(root, meta):
    """The variables a task's commands run with: its own cache, ports and compose project, then the manifest's env."""
    d = task_dir(root, meta["task"])
    out = {"ADK_TASK": meta["task"], "ADK_TASK_DIR": d, "ADK_TASK_CACHE": os.path.join(d, CACHE),
           "ADK_PORT_OFFSET": str(meta["runtime"].get("port_offset", 0)),
           "COMPOSE_PROJECT_NAME": re.sub(r"[^a-z0-9_-]", "-", meta["task"].lower())}
    scope = dict(os.environ, **out)
    for k, v in meta.get("env", {}).items():
        v = re.sub(r"\$\{(\w+)\}|\$(\w+)", lambda m: scope.get(m.group(1) or m.group(2), m.group(0)), str(v))
        out[k] = scope[k] = v
    return out


def run_env(root, meta):
    os.makedirs(os.path.join(task_dir(root, meta["task"]), CACHE), exist_ok=True)
    return dict(os.environ, **task_env(root, meta))


def write_env(root, meta):
    lines = [f"# Task {meta['task']}'s environment - generated by wt.py; set your own in task.json \"env\", then",
             f"# wt.py refresh {meta['task']}. Use it for commands of your own: . ./{ENVFILE} && <command>"]
    lines += [f"export {k}={shlex.quote(v)}" for k, v in task_env(root, meta).items()]
    with open(os.path.join(task_dir(root, meta["task"]), ENVFILE), "w") as f:
        f.write("\n".join(lines) + "\n")


def version_of(r, branch):
    if r.get("role") == "dependency":
        return f"`{r['ref']}` (`{r['commit'][:10]}`)"
    return f"branch `{branch}`"


def write_claude_md(root, meta):
    """The task folder's CLAUDE.md: what the task is, each repository's role, and how to check it as a whole."""
    d = task_dir(root, meta["task"])
    task, repos = meta["task"], meta["repositories"]
    wt = "wt.py"
    owners = any(r.get("owner") for r in repos.values())
    lines = [BEGIN, f"# Task: {task}", ""]
    if meta.get("note"):
        lines += [meta["note"], ""]
    lines += ["This folder is the task's workspace, not a repository: run git per folder (`git -C <folder> ...`), "
              "and commit, push and open a pull request in each edit repository separately. The manifest is "
              f"`{MANIFEST}`.", "",
              "| Folder | Role | Version | Base |" + (" Owner |" if owners else ""),
              "|---|---|---|---|" + ("---|" if owners else "")]
    for name, r in repos.items():
        role = "dependency - do not edit" if r.get("role") == "dependency" else "edit"
        lines.append(f"| `{name}/` | {role} | {version_of(r, meta['branch'])} | "
                     f"{'`' + r['base'] + '`' if r.get('base') else '-'} |"
                     + (f" {r.get('owner') or '-'} |" if owners else ""))
    lines.append("")
    if any(r.get("role") == "dependency" for r in repos.values()):
        lines.append("- **Dependencies are pinned** for this task: read them and build against them, never change "
                     "them. A change one needs makes it an edit repository - ask first.")
    if owners:
        lines.append("- **Owners:** change only the folders you own; anything else goes back to whoever "
                     "coordinates the task.")
    check = (f"`{wt} check {task}` runs the manifest's build and test here, together, and records the "
             f"commit of every repository it ran on in `{CHECKS}`." if meta["build"] or meta["test"] else
             f"The manifest has no build or test commands yet: add them to `{MANIFEST}` (`\"build\"`, `\"test\"`), "
             f"then `{wt} check {task}`.")
    lines += [f"- **Check the task as a whole**, not one repository at a time: {check}",
              f"- **Commands of your own** (a server, a one-off test) run with the task's environment - its own "
              f"ports, compose project and cache folder: `. ./{ENVFILE} && <command>`.",
              f"- After editing `{MANIFEST}` by hand: `{wt} refresh {task}`.",
              f"- `wt.py` is the worktrees skill's script - `python3 {SCRIPT}` as of the last refresh; after the "
              "plugin updates, the skill's own folder has it."]
    imports = [f"@{name}/CLAUDE.md" for name in repos if os.path.isfile(os.path.join(d, name, "CLAUDE.md"))]
    if imports:
        lines += ["", "Each repository's own instructions:", *imports]
    block = "\n".join(lines + [END])
    path = os.path.join(d, "CLAUDE.md")
    try:
        with open(path) as f:
            text = f.read()
    except FileNotFoundError:
        text = ""
    if BEGIN in text and END in text:
        text = text[:text.index(BEGIN)] + block + text[text.index(END) + len(END):]
    elif "<!-- adk-worktrees:" in text and END in text:   # 0.21's block, under its older marker
        text = text[:text.index("<!-- adk-worktrees:")] + block + text[text.index(END) + len(END):]
    else:
        text = block + "\n" + (("\n" + text) if text else "")
    with open(path, "w") as f:
        f.write(text)


def copy_into(name, entry, path):
    for rel in entry.get("copy", []):
        s, d = os.path.join(entry["path"], rel), os.path.join(path, rel)
        if os.path.exists(s) and not os.path.exists(d):
            os.makedirs(os.path.dirname(d), exist_ok=True)
            (shutil.copytree if os.path.isdir(s) else shutil.copy2)(s, d)
            print(f"  {name}: copied {rel} from the main checkout")


def attach_edit(name, entry, path, branch, base):
    """Create the worktree on the task's branch; returns whether the branch was created here (so a rollback deletes it)."""
    src = entry["path"]
    if ok(src, "show-ref", "--verify", "-q", f"refs/heads/{branch}"):
        git(src, "worktree", "add", path, branch)
        created = False
    elif ok(src, "show-ref", "--verify", "-q", f"refs/remotes/origin/{branch}"):
        git(src, "worktree", "add", "--track", "-b", branch, path, f"origin/{branch}")
        created = True
    else:
        if not ok(src, "rev-parse", "-q", "--verify", base + "^{commit}"):
            raise Fail(f"{name}: base {base} does not exist")
        git(src, "worktree", "add", "--no-track", "-b", branch, path, base)
        created = True
    copy_into(name, entry, path)
    return created


def attach_dep(name, entry, path, ref, commit=None):
    """Create the worktree detached at the pinned commit; returns (ref, sha)."""
    src = entry["path"]
    if commit and ok(src, "cat-file", "-e", commit + "^{commit}"):
        sha = git(src, "rev-parse", commit + "^{commit}")
    else:
        resolved, sha = resolve_ref(src, ref)
        if not sha:
            raise Fail(f"{name}: {ref} does not exist")
        if commit:
            print(f"  {name}: the recorded commit {commit[:10]} is not here - using {resolved} at {sha[:10]}")
        ref = resolved
    git(src, "worktree", "add", "--detach", path, sha)
    copy_into(name, entry, path)
    return ref, sha


def setup(name, entry, path, env):
    if entry.get("setup"):
        print(f"  {name}: {entry['setup']}")
        if subprocess.run(entry["setup"], shell=True, cwd=path, env=env).returncode:
            print(f"  {name}: setup failed - the worktree is there; run it again by hand")


def plan(cfg, specs, role):
    out = []
    for spec in specs:
        arg, want = split_spec(spec)
        name, entry = resolve_repo(cfg, arg)
        out.append({"name": name, "entry": entry, "role": role, "want": want})
    return out


def add_repos(root, meta, items, do_fetch):
    """Attach each repository to the task, all or none: a failure removes what this call created."""
    d = task_dir(root, meta["task"])
    names = [i["name"] for i in items]
    for n in names:
        if n in meta["repositories"] or names.count(n) > 1:
            raise Fail(f"{n} is already in task {meta['task']}")
        if n in GENERATED or n in (CHECKS, CACHE) or any(e["destination"].split("/")[0] == n
                                                          for e in meta["external_paths"]):
            raise Fail(f"{n}: the task folder already uses that name")
    made = []
    try:
        for i in items:
            name, entry = i["name"], i["entry"]
            src = entry["path"]
            if do_fetch:
                warn = fetch(src)
                if warn:
                    print(f"  {name}: {warn}")
            path = os.path.join(d, name)
            record = {"role": i["role"], "url": origin_url(src), "source": src}
            if i.get("owner"):
                record["owner"] = i["owner"]
            if i["role"] == "dependency":
                ref, sha = attach_dep(name, entry, path, i["want"] or default_base(src), i.get("commit"))
                made.append((name, src, path, False))
                record.update(ref=ref, commit=sha)
                print(f"  {name}: {os.path.relpath(path, root)} pinned at {ref} ({sha[:10]})")
            else:
                base = i["want"] or meta.get("base") or default_base(src)
                made.append((name, src, path, attach_edit(name, entry, path, meta["branch"], base)))
                record.update(base=base, start=git(path, "rev-parse", "HEAD"))
                print(f"  {name}: {os.path.relpath(path, root)} on {meta['branch']} (base {base})")
            meta["repositories"][name] = record
    except Exception:
        for name, src, path, created in reversed(made):
            git(src, "worktree", "remove", "--force", path, check=False)
            if created:
                git(src, "branch", "-D", meta["branch"], check=False)
            meta["repositories"].pop(name, None)
        raise
    env = run_env(root, meta)
    for i in items:
        setup(i["name"], i["entry"], os.path.join(d, i["name"]), env)


def parse_extras(specs):
    out = []
    for spec in specs or []:
        src, _, dest = spec.partition(":")
        out.append({"source": src, "destination": dest or os.path.basename(os.path.normpath(src))})
    return out


def check_extras(root, meta, extras):
    d = task_dir(root, meta["task"])
    for e in extras:
        dest = os.path.normpath(os.path.join(d, e["destination"]))
        top = os.path.relpath(dest, d).split(os.sep)[0]
        if not dest.startswith(d + os.sep) or top in meta["repositories"] or top in GENERATED + (CHECKS, CACHE):
            raise Fail(f"{e['destination']}: not a free place inside the task folder")
        if not os.path.exists(os.path.expanduser(e["source"])):
            raise Fail(f"{e['source']}: not found")


def copy_extras(root, meta, extras):
    """External files and folders (sample data, local config) are copied, never linked: a task's tests write there."""
    d = task_dir(root, meta["task"])
    for e in extras:
        src, dest = os.path.expanduser(e["source"]), os.path.join(d, e["destination"])
        if os.path.exists(dest):
            print(f"  {e['destination']}: already there, kept")
            continue
        os.makedirs(os.path.dirname(dest), exist_ok=True)
        (shutil.copytree if os.path.isdir(src) else shutil.copy2)(src, dest)
        print(f"  {e['destination']}: copied from {e['source']}")


# ---------------------------------------------------------------- state

def edit_state(path, r):
    if not os.path.isdir(path):
        return {"role": "edit", "state": "missing"}
    base = r["base"]
    head = git(path, "rev-parse", "HEAD", check=False).stdout.strip()
    branch = git(path, "symbolic-ref", "-q", "--short", "HEAD", check=False).stdout.strip() or "(detached)"
    dirty = len(git(path, "status", "--porcelain", "--untracked-files=normal").splitlines())
    counts = git(path, "rev-list", "--left-right", "--count", f"{base}...HEAD", check=False)
    behind = ahead = None
    if counts.returncode == 0:
        behind, ahead = (int(x) for x in counts.stdout.split())
    if git(path, "remote").split():
        unpushed = count(path, "rev-list", "--count", "HEAD", "--not", "--remotes")
    else:
        unpushed = ahead
    track = git(path, "for-each-ref", "--format=%(upstream:short)|%(upstream:track)", f"refs/heads/{branch}",
                check=False).stdout.strip()
    upstream, _, t = track.partition("|")
    gone = "[gone]" in t
    if dirty:
        state = "uncommitted"
    elif unpushed and gone:
        state = "remote-gone"          # typical after a squash merge deleted the remote branch
    elif unpushed:
        state = "unpushed"
    elif ahead is None:
        state = "unknown"              # its base is gone: what the branch holds cannot be told
    elif ahead == 0 and head == r.get("start"):
        state = "new"                  # nothing done yet
    elif ahead == 0:
        state = "in-base"              # everything on the branch is already in its base
    else:
        state = "pushed"
    return {"role": "edit", "state": state, "head": head, "branch": branch, "ahead": ahead, "behind": behind,
            "uncommitted": dirty, "unpushed": unpushed, "upstream": upstream or None, "upstream_gone": gone,
            "base": base}


def dep_state(path, r):
    """A dependency's tracked files only: untracked files in it are what a build left there."""
    if not os.path.isdir(path):
        return {"role": "dependency", "state": "missing"}
    head = git(path, "rev-parse", "HEAD", check=False).stdout.strip()
    dirty = len(git(path, "status", "--porcelain", "--untracked-files=no").splitlines())
    unsaved = count(path, "rev-list", "--count", "HEAD", "--not", "--branches", "--remotes", "--tags") or 0
    state = "modified" if dirty else "moved" if head != r["commit"] else "pinned"
    return {"role": "dependency", "state": state, "head": head, "ref": r["ref"], "commit": r["commit"],
            "uncommitted": dirty, "unsaved": unsaved}


def repo_state(root, meta, name):
    r = meta["repositories"][name]
    path = os.path.join(task_dir(root, meta["task"]), name)
    return dep_state(path, r) if r.get("role") == "dependency" else edit_state(path, r)


def holds_work(s):
    if s["role"] == "dependency":
        return s["state"] != "missing" and (s["uncommitted"] or s["unsaved"])
    return s["state"] in ("uncommitted", "unpushed", "remote-gone", "unknown")


def last_check(root, task):
    try:
        with open(os.path.join(task_dir(root, task), CHECKS)) as f:
            lines = [l for l in f.read().splitlines() if l.strip()]
    except FileNotFoundError:
        return None
    return json.loads(lines[-1]) if lines else None


def changed_since(check, repos):
    then = check.get("repositories", {})
    return sorted(n for n, s in repos.items()
                  if n not in then or s.get("head") != then[n].get("commit")
                  or s.get("uncommitted") != then[n].get("uncommitted"))


def task_state(root, task, do_fetch=False):
    meta = load_task(root, task)
    out = {"task": task, "branch": meta["branch"], "note": meta.get("note"), "repos": {}}
    for name, r in meta["repositories"].items():
        if do_fetch and os.path.isdir(r["source"]):
            fetch(r["source"])
        out["repos"][name] = repo_state(root, meta, name)
    check = last_check(root, task)
    if check:
        out["last_check"] = {"at": check["at"], "result": check["result"],
                             "changed_since": changed_since(check, out["repos"])}
    return out


def strays(cfg, root):
    """Worktrees of registered repositories that are outside the root (the kit's own unit worktrees aside)."""
    found = []
    for name, entry in sorted(cfg["repos"].items()):
        src = entry["path"]
        if not os.path.isdir(src):
            continue
        for line in git(src, "worktree", "list", "--porcelain", check=False).stdout.splitlines():
            if not line.startswith("worktree "):
                continue
            p = os.path.realpath(line[9:])
            if p == os.path.realpath(src) or p.startswith(root + os.sep) or "/.claude/worktrees/" in p:
                continue
            found.append((name, p))
    return found


def fmt(v):
    return "-" if v is None else str(v)


# ---------------------------------------------------------------- commands

def cmd_init(cfg, a):
    def change(c):
        if a.root:
            root = os.path.realpath(os.path.expanduser(a.root))
            os.makedirs(root, exist_ok=True)
            c["root"] = root
        if a.sources:
            c["sources"] = os.path.realpath(os.path.expanduser(a.sources))
    if a.root or a.sources:
        update_config(cfg, change)
    print(f"config:  {config_path()}")
    print(f"root:    {cfg.get('root') or '(not set)'}")
    print(f"sources: {cfg.get('sources') or '(not set - restore clones nothing)'}")
    print(f"repos:   {', '.join(sorted(cfg['repos'])) or '(none)'}")


def cmd_repo(cfg, a):
    if a.repo_cmd == "add":
        path = os.path.realpath(os.path.expanduser(a.path))
        if not os.path.isdir(path) or not ok(path, "rev-parse", "--git-dir"):
            raise Fail(f"{a.path} is not a git checkout")
        entry = {"path": main_checkout(path)}
        if a.copy:
            entry["copy"] = a.copy
        if a.setup:
            entry["setup"] = a.setup
        update_config(cfg, lambda c: c["repos"].__setitem__(a.name, entry))
        print(f"{a.name} -> {entry['path']}")
    elif a.repo_cmd == "remove":
        if not update_config(cfg, lambda c: c["repos"].pop(a.name, None)):
            raise Fail(f"no repository named {a.name}")
        print(f"forgot {a.name} (its checkout and worktrees are untouched)")
    else:
        for name, e in sorted(cfg["repos"].items()):
            extra = "".join([f"  copy {','.join(e['copy'])}" if e.get("copy") else "",
                             f"  setup `{e['setup']}`" if e.get("setup") else ""])
            print(f"{name}  {e['path']}{extra}")


def valid_task_name(task):
    if not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9._-]*", task):
        raise Fail(f"task name {task!r}: letters, digits, '.', '_' and '-' only - it is a folder name")


def create(root, meta, items, extras, do_fetch):
    d = task_dir(root, meta["task"])
    if os.path.exists(d):
        raise Fail(f"{d} already exists - wt.py add {meta['task']} <repo> to bring in another repository")
    if not items:
        raise Fail("a task needs at least one repository")
    meta["external_paths"] = extras
    check_extras(root, meta, extras)
    os.makedirs(d)
    print(f"task {meta['task']} at {d}")
    try:
        add_repos(root, meta, items, do_fetch)
        check_extras(root, meta, extras)          # again: now that the repositories have their names
        copy_extras(root, meta, extras)
    except BaseException:
        for name, r in meta["repositories"].items():
            git(r["source"], "worktree", "remove", "--force", os.path.join(d, name), check=False)
        shutil.rmtree(d, ignore_errors=True)
        raise
    save_task(root, meta)
    print(f"open it: cd {d}")


def cmd_new(cfg, a):
    root = root_of(cfg)
    valid_task_name(a.task)
    branch = a.branch or a.task
    if subprocess.run(["git", "check-ref-format", "--branch", branch], capture_output=True).returncode:
        raise Fail(f"{branch!r} is not a valid branch name")
    meta = normalize({"task": a.task, "branch": branch, "created": time.strftime("%Y-%m-%d"), "repositories": {}})
    if a.base:
        meta["base"] = a.base
    if a.note:
        meta["note"] = a.note
    meta["build"], meta["test"] = a.build or [], a.test or []
    items = plan(cfg, a.repos, "edit") + plan(cfg, a.dep or [], "dependency")
    create(root, meta, items, parse_extras(a.extra), not a.no_fetch)


def cmd_restore(cfg, a):
    root = root_of(cfg)
    with open(os.path.expanduser(a.manifest)) as f:
        src = normalize(json.load(f))
    task = a.as_task or src["task"]
    valid_task_name(task)
    meta = normalize({"task": task, "branch": src["branch"], "created": time.strftime("%Y-%m-%d"),
                      "repositories": {}})
    for k in ("base", "note", "build", "test", "env"):
        if src.get(k):
            meta[k] = src[k]
    items = []
    for name, r in src["repositories"].items():
        dep = r.get("role") == "dependency"
        items.append({"name": name, "entry": locate(cfg, name, r), "role": "dependency" if dep else "edit",
                      "want": r.get("ref") if dep else r.get("base"), "commit": r.get("commit") if dep else None,
                      "owner": r.get("owner")})
    create(root, meta, items, src["external_paths"], not a.no_fetch)


def cmd_add(cfg, a):
    root = root_of(cfg)
    meta = load_task(root, a.task)
    items = plan(cfg, a.repos, "edit") + plan(cfg, a.dep or [], "dependency")
    if not items:
        raise Fail("name a repository to add")
    add_repos(root, meta, items, not a.no_fetch)
    save_task(root, meta)


def cmd_pin(cfg, a):
    root = root_of(cfg)
    meta = load_task(root, a.task)
    r = meta["repositories"].get(a.repo)
    if not r or r.get("role") != "dependency":
        raise Fail(f"{a.repo} is not a dependency of {a.task}")
    s = repo_state(root, meta, a.repo)
    if s["state"] == "missing":
        raise Fail(f"{a.repo}: the folder is gone")
    if holds_work(s):
        raise Fail(f"{a.repo} holds changes of its own ({s['uncommitted']} uncommitted, {s['unsaved']} commit(s) "
                   "on no branch) - a dependency is not edited; move them out first")
    if not a.no_fetch:
        warn = fetch(r["source"])
        if warn:
            print(f"  {a.repo}: {warn}")
    ref, sha = resolve_ref(r["source"], a.ref)
    if not sha:
        raise Fail(f"{a.repo}: {a.ref} does not exist")
    git(os.path.join(task_dir(root, a.task), a.repo), "checkout", "-q", "--detach", sha)
    r.update(ref=ref, commit=sha)
    save_task(root, meta)
    print(f"  {a.repo}: pinned at {ref} ({sha[:10]}) - check the task again: wt.py check {a.task}")


def cmd_refresh(cfg, a):
    root = root_of(cfg)
    save_task(root, load_task(root, a.task))
    print(f"refreshed CLAUDE.md and {ENVFILE} of {a.task}")


def cmd_status(cfg, a):
    root = root_of(cfg)
    tasks = a.tasks or all_tasks(root)
    states = [task_state(root, t, a.fetch) for t in tasks]
    others = [] if a.tasks else strays(cfg, root)
    if a.json:
        print(json.dumps({"root": root, "tasks": states,
                          "outside_root": [{"repo": n, "path": p} for n, p in others]}, indent=2))
        return
    if not states:
        print(f"No tasks under {root}.")
    for s in states:
        print(f"{s['task']}  branch {s['branch']}" + (f"  - {s['note']}" if s.get("note") else ""))
        width = max(len(n) for n in s["repos"]) if s["repos"] else 0
        for name, r in s["repos"].items():
            if r["state"] == "missing":
                print(f"  {name:<{width}}  missing - the folder is gone")
            elif r["role"] == "dependency":
                print(f"  {name:<{width}}  {r['state']:<11}  dependency at {r['ref']} ({r['commit'][:10]})"
                      + (f"  now {r['head'][:10]}" if r["state"] == "moved" else "")
                      + (f"  {r['uncommitted']} file(s) changed" if r["uncommitted"] else ""))
            else:
                print(f"  {name:<{width}}  {r['state']:<11}  ahead {fmt(r['ahead'])}  behind {fmt(r['behind'])}"
                      f"  uncommitted {r['uncommitted']}  unpushed {fmt(r['unpushed'])}  base {r['base']}"
                      + ("" if r["branch"] == s["branch"] else f"  (on {r['branch']}, not the task's branch)"))
        c = s.get("last_check")
        if c:
            since = c["changed_since"]
            print(f"  last check {c['at']}: {c['result']}"
                  + (f"; changed since: {', '.join(since)}" if since else "; nothing changed since"))
    if others:
        print("\nWorktrees outside the root:")
        for name, p in others:
            print(f"  {name}  {p}")


def cmd_sync(cfg, a):
    root = root_of(cfg)
    meta = load_task(root, a.task)
    failed = moved = False
    for name, r in meta["repositories"].items():
        if r.get("role") == "dependency":
            print(f"  {name}: a dependency, pinned at {r['ref']} - wt.py pin {a.task} {name} <ref> to move it")
            continue
        path = os.path.join(task_dir(root, a.task), name)
        if not a.no_fetch:
            warn = fetch(r["source"])
            if warn:
                print(f"  {name}: {warn}")
        s = edit_state(path, r)
        skip = None
        if s["state"] == "missing":
            skip = "missing - the folder is gone"
        elif s["uncommitted"]:
            skip = f"skipped - {s['uncommitted']} uncommitted change(s); commit or stash first"
        elif s["behind"] is None:
            skip = f"skipped - its base {r['base']} does not exist"
        elif a.rebase and s["upstream"] and count(path, "rev-list", "--count", f"{r['base']}..{s['upstream']}"):
            skip = "skipped - the branch is pushed; rebasing would need a force push. Sync without --rebase"
        if skip:
            print(f"  {name}: {skip}")
            failed = True
            continue
        if s["behind"] == 0:
            print(f"  {name}: up to date with {r['base']}")
            continue
        step = ["rebase", r["base"]] if a.rebase else ["merge", "--no-edit", r["base"]]
        if ok(path, *step):
            print(f"  {name}: {'rebased onto' if a.rebase else 'merged'} {r['base']} ({s['behind']} commit(s))")
            if s["state"] == "new":            # still nothing done: the new start is where it now is
                r["start"] = git(path, "rev-parse", "HEAD")
                moved = True
            continue
        conflicts = git(path, "diff", "--name-only", "--diff-filter=U", check=False).stdout.split()
        git(path, step[0], "--abort", check=False)
        print(f"  {name}: conflicts with {r['base']} in {', '.join(conflicts) or 'the tree'} - left as it was; "
              f"run `git -C {name} {' '.join(step)}` and resolve them")
        failed = True
    if moved:
        save_task(root, meta)
    return 1 if failed else 0


def command_of(argv):
    cmd = argv[1:] if argv and argv[0] == "--" else argv
    if not cmd:
        return None
    return cmd[0] if len(cmd) == 1 else shlex.join(cmd)  # one argument is a shell line, as typed


def cmd_run(cfg, a):
    root = root_of(cfg)
    meta = load_task(root, a.task)
    argv = list(a.command)
    if argv[:1] == ["--all"]:              # argparse leaves an option after TASK in the command
        a.all, argv = True, argv[1:]
    cmd = command_of(argv)
    if not cmd:
        raise Fail("nothing to run: wt.py run TASK -- <command>")
    env = run_env(root, meta)
    failed = []
    for name, r in meta["repositories"].items():
        if r.get("role") == "dependency" and not a.all:
            continue
        print(f"== {name}", flush=True)
        rc = subprocess.run(cmd, shell=True, cwd=os.path.join(task_dir(root, a.task), name), env=env).returncode
        if rc:
            failed.append(f"{name} ({rc})")
    if failed:
        print(f"failed in: {', '.join(failed)}")
    return 1 if failed else 0


def snapshot(root, meta):
    out = {}
    for name in meta["repositories"]:
        s = repo_state(root, meta, name)
        out[name] = {"role": s["role"], "commit": s.get("head"), "uncommitted": s.get("uncommitted")}
        if s["role"] == "dependency":
            out[name]["ref"] = s["ref"]
        elif s.get("branch"):
            out[name]["branch"] = s["branch"]
    return out


def cmd_check(cfg, a):
    root = root_of(cfg)
    meta = load_task(root, a.task)
    d = task_dir(root, a.task)
    adhoc = command_of(a.command)
    steps = [("command", adhoc)] if adhoc else \
        [("build", c) for c in meta["build"]] + [("test", c) for c in meta["test"]]
    if not steps:
        raise Fail(f"{a.task} has no build or test commands: add them to {os.path.join(d, MANIFEST)} "
                   f"(\"build\": [...], \"test\": [...]), or pass one: wt.py check {a.task} -- <command>")
    env = run_env(root, meta)
    before = snapshot(root, meta)
    results, passed = [], True
    for kind, c in steps:
        print(f"== {kind}: {c}", flush=True)
        rc = subprocess.run(c, shell=True, cwd=d, env=env).returncode
        results.append({"step": kind, "command": c, "exit": rc})
        if rc:
            passed = False
            break
    after = snapshot(root, meta)
    record = {"at": time.strftime("%Y-%m-%dT%H:%M:%S"), "result": "passed" if passed else "failed",
              "steps": results, "repositories": after}
    changed = [n for n in after if after[n] != before.get(n)]
    if changed:
        record["changed_during"] = changed
    with open(os.path.join(d, CHECKS), "a") as f:
        f.write(json.dumps(record) + "\n")
    dirty = [n for n, s in after.items() if s["uncommitted"]]
    print(f"{record['result']} - recorded with the commit of every repository in {CHECKS}"
          + (f"; uncommitted changes in {', '.join(dirty)} are part of what ran" if dirty else "")
          + (f"; changed while it ran: {', '.join(changed)}" if changed else ""))
    return 0 if passed else 1


def remove_task(root, task, force):
    meta = load_task(root, task)
    d = task_dir(root, task)
    states = {n: repo_state(root, meta, n) for n in meta["repositories"]}
    holding = {n: s for n, s in states.items() if holds_work(s)}
    if holding and not force:
        lines = []
        for n, s in holding.items():
            if s["role"] == "dependency":
                lines.append(f"  {n}: a dependency with {s['uncommitted']} changed file(s) and {s['unsaved']} "
                             "commit(s) on no branch")
            elif s["state"] == "unknown":
                lines.append(f"  {n}: its base {s['base']} is gone, so what the branch holds cannot be told")
            else:
                lines.append(f"  {n}: {s['uncommitted']} uncommitted, {fmt(s['unpushed'])} unpushed commit(s)"
                             + (" - its remote branch is gone: if the pull request was merged (squash), --force "
                                "is safe" if s["upstream_gone"] else ""))
        raise Fail(f"{task} holds work that would be lost:\n" + "\n".join(lines) +
                   "\nPush or commit it, or pass --force: uncommitted changes are saved as a patch and "
                   "branches with unpushed commits are kept.")
    keep = os.path.join(root, ".removed", task)
    for name, r in meta["repositories"].items():
        path, s = os.path.join(d, name), states[name]
        dep = s["role"] == "dependency"
        if s["state"] != "missing":
            if s["uncommitted"]:
                os.makedirs(keep, exist_ok=True)
                patch = os.path.join(keep, f"{name}.patch")
                if not dep:
                    git(path, "add", "-A", "-N", ".", check=False)
                with open(patch, "w") as f:
                    f.write(git(path, "diff", "--binary", "HEAD", check=False).stdout)
                print(f"  {name}: uncommitted changes saved to {patch}")
            if dep and s["unsaved"]:
                saved = f"wt-saved/{task}/{name}"
                git(r["source"], "branch", "-f", saved, s["head"])
                print(f"  {name}: {s['unsaved']} commit(s) on no branch kept as branch {saved}")
            git(r["source"], "worktree", "remove", "--force", path)
        git(r["source"], "worktree", "prune", check=False)
        if dep:
            print(f"  {name}: removed")
        elif s.get("unpushed") or s["state"] == "unknown":
            print(f"  {name}: removed; kept branch {meta['branch']}"
                  + (f" ({s['unpushed']} unpushed commit(s))" if s.get("unpushed") else ""))
        elif ok(r["source"], "branch", "-d", meta["branch"]):
            print(f"  {name}: removed, with its branch")
        else:
            print(f"  {name}: removed; kept branch {meta['branch']} (not merged locally)")
    os.makedirs(keep, exist_ok=True)
    for f in (MANIFEST, LEGACY, CHECKS):
        if os.path.exists(os.path.join(d, f)):
            shutil.move(os.path.join(d, f), os.path.join(keep, MANIFEST if f == LEGACY else f))
    for f in ("CLAUDE.md", ENVFILE):
        if os.path.exists(os.path.join(d, f)):
            os.remove(os.path.join(d, f))
    shutil.rmtree(os.path.join(d, CACHE), ignore_errors=True)
    for e in meta["external_paths"]:
        dest = os.path.join(d, e["destination"])
        if os.path.isdir(dest) and not os.path.islink(dest):
            shutil.rmtree(dest)
        elif os.path.lexists(dest):
            os.remove(dest)
    left = os.listdir(d) if os.path.isdir(d) else []
    if left:
        print(f"  kept {d}: it still holds {', '.join(sorted(left))}")
    else:
        os.rmdir(d)
        print(f"removed {task} - its manifest is kept: wt.py restore {os.path.join(keep, MANIFEST)}")


def cmd_remove(cfg, a):
    remove_task(root_of(cfg), a.task, a.force)


def cmd_prune(cfg, a):
    root = root_of(cfg)
    done, check, untouched = [], [], []
    for t in all_tasks(root):
        s = task_state(root, t, not a.no_fetch)
        edits = {r["state"] for r in s["repos"].values() if r["role"] == "edit"}
        deps_hold = any(holds_work(r) for r in s["repos"].values() if r["role"] == "dependency")
        if edits and edits <= {"in-base", "missing"} and "in-base" in edits and not deps_hold:
            done.append(t)
        elif "remote-gone" in edits:
            check.append(t)
        elif edits and edits <= {"new", "in-base", "missing"}:
            untouched.append(t)
    for t in done:
        if a.yes:
            remove_task(root, t, False)
        else:
            print(f"would remove {t}: every branch is already in its base")
    for t in check:
        print(f"check {t}: a remote branch is gone but its commits are not in the base - "
              "if its pull requests were squash-merged, wt.py remove --force")
    for t in untouched:
        print(f"kept {t}: nothing done in it yet - wt.py remove {t} if it is not needed")
    if not done and not check and not untouched:
        print("Nothing to prune.")
    elif done and not a.yes:
        print("Run again with --yes to remove them.")


def parser():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = p.add_subparsers(dest="cmd", required=True)
    s = sub.add_parser("init")
    s.add_argument("--root")
    s.add_argument("--sources", help="where restore clones a repository this machine does not have")

    repo = sub.add_parser("repo").add_subparsers(dest="repo_cmd", required=True)
    r = repo.add_parser("add")
    r.add_argument("name")
    r.add_argument("path")
    r.add_argument("--copy", action="append", help="an untracked file to copy into each new worktree, e.g. .env")
    r.add_argument("--setup", help="a command to run in each new worktree, e.g. 'npm ci'")
    repo.add_parser("list")
    repo.add_parser("remove").add_argument("name")

    def repos_args(s):
        s.add_argument("repos", nargs="*", help="repositories to edit: REPO or REPO@BASE")
        s.add_argument("--dep", action="append", help="a dependency, pinned: REPO or REPO@REF (repeatable)")
        s.add_argument("--no-fetch", action="store_true")

    s = sub.add_parser("new")
    s.add_argument("task")
    repos_args(s)
    s.add_argument("--branch", help="default: the task name")
    s.add_argument("--base", help="default: each repository's origin/HEAD")
    s.add_argument("--note", help="one line on what the task is, for its CLAUDE.md")
    s.add_argument("--extra", action="append", help="SRC[:DEST] - a file or folder copied into the task folder")
    s.add_argument("--build", action="append", help="the task's build command, run in the task folder (repeatable)")
    s.add_argument("--test", action="append", help="the task's test command, run in the task folder (repeatable)")

    s = sub.add_parser("restore")
    s.add_argument("manifest")
    s.add_argument("--as", dest="as_task", help="another task name")
    s.add_argument("--no-fetch", action="store_true")

    s = sub.add_parser("add")
    s.add_argument("task")
    repos_args(s)

    s = sub.add_parser("pin")
    s.add_argument("task")
    s.add_argument("repo")
    s.add_argument("ref")
    s.add_argument("--no-fetch", action="store_true")

    sub.add_parser("refresh").add_argument("task")

    s = sub.add_parser("status")
    s.add_argument("tasks", nargs="*")
    s.add_argument("--fetch", action="store_true")
    s.add_argument("--json", action="store_true")

    s = sub.add_parser("sync")
    s.add_argument("task")
    s.add_argument("--rebase", action="store_true")
    s.add_argument("--no-fetch", action="store_true")

    s = sub.add_parser("run")
    s.add_argument("task")
    s.add_argument("--all", action="store_true", help="dependencies too")
    s.add_argument("command", nargs=argparse.REMAINDER)

    s = sub.add_parser("check")
    s.add_argument("task")
    s.add_argument("command", nargs=argparse.REMAINDER)

    s = sub.add_parser("remove")
    s.add_argument("task")
    s.add_argument("--force", action="store_true")

    s = sub.add_parser("prune")
    s.add_argument("--yes", action="store_true")
    s.add_argument("--no-fetch", action="store_true")
    return p


def main(argv=None):
    p = parser()
    a = p.parse_args(argv)
    try:
        return globals()["cmd_" + a.cmd](load_config(), a) or 0
    except Fail as e:
        print(f"wt.py: {e}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
